import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';

// Load Bootstrap once at the app root so every component can use it.
import 'bootstrap/dist/css/bootstrap.min.css';
import './index.css';

import App from './App';
import { AuthProvider } from './context/AuthContext';
import * as serviceWorkerRegistration from './serviceWorkerRegistration';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <BrowserRouter>
      <AuthProvider>
        <App />
      </AuthProvider>
    </BrowserRouter>
  </React.StrictMode>
);

// ── Service Worker (PWA) ─────────────────────────────────────────────────────
// Register the Workbox service worker generated by CRA at build time.
// This enables offline caching and makes the app installable.
//
// onUpdate: a new version was deployed — prompt the user to refresh.
// onSuccess: first-time install — app is now ready for offline use.
serviceWorkerRegistration.register({
  onUpdate: (registration) => {
    const waitingWorker = registration.waiting;
    if (waitingWorker) {
      waitingWorker.postMessage({ type: 'SKIP_WAITING' });
    }
    // Show a subtle reload notification
    const banner = document.createElement('div');
    banner.id = 'sw-update-banner';
    banner.innerHTML = `
      <div style="
        position:fixed; bottom:80px; left:50%; transform:translateX(-50%);
        background:#0d6efd; color:#fff; padding:12px 20px; border-radius:12px;
        font-size:0.88rem; font-weight:600; z-index:9999; display:flex;
        align-items:center; gap:12px; box-shadow:0 4px 20px rgba(13,110,253,0.4);
        max-width:340px; width:90%; animation: swSlideUp 0.35s ease;
      ">
        <span>🎉 New version available!</span>
        <button onclick="window.location.reload()" style="
          background:rgba(255,255,255,0.2); border:1px solid rgba(255,255,255,0.4);
          color:#fff; border-radius:8px; padding:4px 12px; cursor:pointer;
          font-weight:700; font-size:0.85rem; white-space:nowrap;
        ">Reload</button>
      </div>`;
    document.body.appendChild(banner);
  },
  onSuccess: () => {
    console.log('[SW] Billing System is ready for offline use.');
  },
});
